
echo Setting myEnvironment ....

EONE_HOME=@EONE_HOME@
export EONE_HOME
JAVA_HOME=@JAVA_HOME@
export JAVA_HOME

#	Database ...
EONE_DB_SERVER=@EONE_DB_SERVER@
export EONE_DB_SERVER
EONE_DB_USER=@EONE_DB_USER@
export EONE_DB_USER
EONE_DB_PASSWORD=@EONE_DB_PASSWORD@
export EONE_DB_PASSWORD
EONE_DB_URL=@EONE_DB_URL@
export EONE_DB_URL
EONE_DB_PORT=@EONE_DB_PORT@
export EONE_DB_PORT

#	Oracle Specifics ...
EONE_DB_PATH=@EONE_DB_PATH@
export EONE_DB_PATH
EONE_DB_NAME=@EONE_DB_NAME@
export EONE_DB_NAME
EONE_DB_SYSTEM=@EONE_DB_SYSTEM@
export EONE_DB_SYSTEM

#	Homes(2)
EONE_DB_HOME=$EONE_HOME/utils/$EONE_DB_PATH
export EONE_DB_HOME

#	Apps Server
EONE_APPS_SERVER=@EONE_APPS_SERVER@
export EONE_APPS_SERVER
EONE_WEB_PORT=@EONE_WEB_PORT@
export EONE_WEB_PORT
EONE_JNP_PORT=@EONE_JNP_PORT@
export EONE_JNP_PORT
#	SSL Settings - see jboss/server/adempiere/deploy/jbossweb.sar/META-INF/jboss-service.xml
EONE_SSL_PORT=@EONE_SSL_PORT@
export EONE_SSL_PORT
EONE_KEYSTORE=@EONE_KEYSTORE@
export EONE_KEYSTORE
EONE_KEYSTOREPASS=@EONE_KEYSTOREPASS@
export EONE_KEYSTOREPASS

#	Java
EONE_JAVA=$JAVA_HOME/bin/java
export EONE_JAVA
EONE_JAVA_OPTIONS="@EONE_JAVA_OPTIONS@ -DEONE_HOME=$EONE_HOME"
export EONE_JAVA_OPTIONS

if [ $DOLLAR$# -eq 0 ] 
  then
    cp $EONE_HOME/utils/myEnvironment.sh $EONE_HOME/utils/myEnvironment.sav
fi